images:
  available_noises: ['nonoise', 'gaussian_noise', 'partial_obs', 'background_noise', 'sensor_fail', 'random_obs']
  background_noise:
    color: [60, 90, 120]
    tolerance: 45
  gaussian_noise:
    mu: 0
    std: 25
  salt_pepper_noise:
    ratio: 0.005
  poisson_noise:
    lam: 10
  speckle_noise:
    mean: 0
    std: 0.1
  uniform_noise:
    min_val: 0
    max_val: 50
  gaussian_blur:
    sigma: 1
  motion_blur:
    kernel_size: 5
    angle: 45
  quantization_noise:
    bits: 16
  confounders_noise:
    max_size: 50
    min_size: 10
    max_num_patches: 3
  img_path: 'bg_images'


depths:
  available_noises: ['nonoise', 'gaussian_noise', 'partial_obs', 'background_noise', 'sensor_fail', 'random_obs']
  bounds:
    min_depth: 5
    max_depth: 50
  background_noise:
    depth: 60
  gaussian_noise:
    mu: 0
    std: 25
  confounders_noise:
    max_size: 50
    min_size: 10
    max_num_patches: 3
  img_path: 'bg_images'



states:
  available_noises: ['nonoise', 'gaussian_noise', 'partial_obs', 'background_noise', 'sensor_fail', 'random_obs']
  gaussian_noise:
    mu: 0
    std: 0.1
  poisson_noise:
    mean: 0.1

rams:
  available_noises: ['nonoise', 'gaussian_noise', 'partial_obs', 'background_noise', 'sensor_fail', 'random_obs']
  gaussian_noise:
    mu: 0
    std: 0.1
  poisson_noise:
    mean: 0.1